import Header from "@components/Header";
import CartModal from "@components/CartModal";
import Footer from "@components/Footer";
import Head from "next/head";
import "@styles/globals.scss";
import { CartContext, useCartState } from "@hooks/use-cart";

function MyApp({ Component, pageProps }) {
  let cart = useCartState();
  return (
    <CartContext.Provider value={cart}>
      <Head>
        <title>Gemma Rutter Masks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <CartModal />
      <Component {...pageProps} />
      <Footer />
    </CartContext.Provider>
  );
}

export default MyApp;
