import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Container from '@components/Container'

import styles from '@styles/Home.module.scss'

import products from '@data/products.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>  
        <Container>
          <h1>Gemma Rutter Masks</h1>
          <h2>Available Masks</h2>
          <ul className={styles.products}>
            {products.map(product => {
              return (
              <li key={product.groupId}>
                <Link href={`/products/${product.groupId}`}>
                  <a>
                    <Image width="4032" height="3024" src={product.variants[0].image} alt={`Card of ${product.groupTitle}`} />
                    <h3 className={styles.productTitle}>{product.groupTitle}</h3>
                    <p className={styles.productPrice}>£{product.variants[0].price}</p>
                    <p>
                      <button>Add To Cart</button>
                    </p>
                  </a>
                </Link>
              </li>
              )
            })}
          </ul>
        </Container>        
      </main>

      <footer className={styles.footer}>
        &copy; Gemma Rutter Masks, {new Date().getFullYear()}
      </footer>
    </div>
  )
}
